<?php

return [
    'roles' => [
        'Tutor' => [
            'dashboard.view',
            'agenda.view',
            'circulares.view',
            'calificaciones.view',
            'tareas.view',
            'asistencia.view',
            'reportes.view',
            'notificaciones.view',
            'horario.view',
        ],
        'Profesor' => [
            'dashboard.view',
            'agenda.view',
            'circulares.view',
            'calificaciones.manage',
            'asistencia.manage',
            'tareas.manage',
            'notificaciones.manage',
            'horario.view',
        ],
        'Trabajador Social' => [
            'dashboard.view',
            'agenda.view',
            'circulares.view',
            'reportes.manage',
            'notificaciones.manage',
            'alumnos.view',
        ],
        'Administrador' => [
            'dashboard.view',
            'usuarios.manage',
            'usuarios.validate',
            'roles.manage',
            'ciclos.manage',
            'periodos.manage',
            'configuracion.manage',
            'grupos.manage',
            'materias.manage',
            'alumnos.manage',
        ],
        'Personal Administrativo' => [
            'dashboard.view',
            'agenda.view',
            'agenda.manage',
            'circulares.view',
            'circulares.manage',
            'horarios.manage',
            'grupos.manage',
            'alumnos.manage',
            'tutores.manage',
        ],
    ],
];
