name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Desplegar
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ secrets.SSH_PATH }}
            cp -r public/build ./build
            if [ ! -L public/storage ]; then
              ln -s /home/u760642468/domains/est75.ssteans.com/public_html/storage/app/public /home/u760642468/domains/est75.ssteans.com/public_html/public/storage
            fi
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache